org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3g -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir=/home/hatch/tmp -Dhttp.proxyHost=hatch-egress-proxy -Dhttp.proxyPort=3128 -Dhttp.proxyUser=hatch-runtime -Dhttp.proxyPassword=a1cea0a2dd1f4cae8bbbf2335982b272 -Dhttps.proxyHost=hatch-egress-proxy -Dhttps.proxyPort=3128 -Dhttps.proxyUser=hatch-runtime -Dhttps.proxyPassword=a1cea0a2dd1f4cae8bbbf2335982b272
android.useAndroidX=false
