android.useAndroidX=true
android.nonTransitiveRClass=true
android.sdk.dir=/home/hatch/android
org.gradle.daemon=false
org.gradle.jvmargs=-Xmx1024m -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir=/home/hatch/workspace/.gradle-tmp -Dhttp.proxyHost=hatch-egress-proxy -Dhttp.proxyPort=3128 -Dhttp.proxyUser=hatch-runtime -Dhttp.proxyPassword=d5443a0b8cd54d44aa9e754c85b1757f -Dhttps.proxyHost=hatch-egress-proxy -Dhttps.proxyPort=3128 -Dhttps.proxyUser=hatch-runtime -Dhttps.proxyPassword=d5443a0b8cd54d44aa9e754c85b1757f
